### ISSUE TITLE
Create getItemIds* functions

### ISSUE THREAD

**Issue by poplav** [poplav/hackernews4r#2]
- get_item_ids_for_top_stories - /topstories.json
- get_item_ids_for_new_stories - /newstories.json
- get_item_ids_for_ask_stories - /askstories.json
- get_item_ids_for_show_stories - /showstories.json

**Comment by bmewing** [comment]
Are you looking for new functions like `get_top_stories` but for new/ask/show stories?

**Comment by poplav** [comment]
Howdy, @bmewing.  Yes, ultimately we are looking for the functions get_(top|new|ask|show)_stories.

The plan would be to create functions such as `get_item_ids_for_top_stories`.  Then a function that takes in an item id and returns the item, `get_item`.  Then the final function `get_top_stories` which gets the list of item ids for the top stories, from the list call get item for each item id, and return the list of items where each item represents the top stories.

I tried to organize this work across multiple issues or prs, so this would be encompassing creating those get_item_ids_for\* functions.  Please liberally open prs and we can iterate together once it is up there.  Note tests are a very nice to have going as well, you will see them get run on a pr by travis.

**Comment by bmewing** [comment]
So, there's already a function that seems to do this, I want to make sure I understand what your needs are so I don't duplicate effort.  The function `get_top_stories` fetches the ids from topstories.json and then gets the urls.  Are you wanting this broken into multiple separate functions or are you wanting something radically different?

`get_top_stories <- function(limit = 10, pretty_print = FALSE) {
    top_stories_ids <- fromJSON(paste(base_url, "/topstories.json", sep=""))
    top_stories_ids <- top_stories_ids[1:limit]
    top_stories <- lapply(top_stories_ids, function(id) {
        story_url <- paste(base_url, "/item/", id, ".json", sep="")
        fromJSON(story_url)
    })
    process_stories(top_stories, pretty_print)
}`

**Comment by poplav** [comment]
Yes, breaking this up into multiple separate functions sounds like what we want.  So, in `get_top_stories` it would look like `lapply(get_item_ids_for_top_stories(), ...get_item(id))`
Then we want to eventually follow this approach for the other top_*

**Comment by smritigambhir** [comment]
@poplav  Please review PR: https://github.com/poplav/hackernews4r/pull/3 and let me know if you have any comments. If this looks okay, I can submit PR for second feature as well.

**Comment by poplav** [comment]
Fixed by #3
