### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by chipsenkbeil** [poplav/hackernews4r#9]
Yo, how's it going, @poplav?

**Comment by poplav** [comment]
Howdy,

![](https://media.giphy.com/media/S1N2zUokK7jiM/giphy.gif)

**Comment by poplav** [comment]
Howdy @chipsenkbeil,

![](https://media.giphy.com/media/S1N2zUokK7jiM/giphy.gif)

**Comment by chipsenkbeil** [comment]
Beautiful.
